### ISSUE TITLE
g3a_predate_catchability_quotafleet issue

### ISSUE THREAD

**Issue by willbutler42** [gadget-framework/gadget3#105]
`g3a_predate_fleet` seems to produce an error if you pass a list of multiple stocks to the `sum_stocks` argument in `g3a_predate_catchability_quotafleet`. Seems that the second stock object is not found:

Error in get(as.character(stock_var), envir = orig_env) : 
  object 'red_mat' not found

A simple illustation is attached
[quotafleet_issue.zip](https://github.com/gadget-framework/gadget3/files/10710117/quotafleet_issue.zip)

**Comment by lentinj** [comment]
Does the above help? The example works, but I've not tested it further yet.

**Comment by willbutler42** [comment]
Thanks, this works : )
