### ISSUE TITLE
Weird growth or ageing in the ling model

### ISSUE THREAD

**Issue by bthe** [gadget-framework/gadget3#11]
I'm annoying close to a working model for the ling:
![image](https://user-images.githubusercontent.com/7022612/107517353-91832900-6ba5-11eb-90ce-439624df06de.png)

but for this solution the fit to the ldists is weird as the model output is jagged:

![image](https://user-images.githubusercontent.com/7022612/107517603-db6c0f00-6ba5-11eb-8d3b-656fb45c962b.png)

Initially I thought this was related to the length at age but this also appears in the size at age:
![image](https://user-images.githubusercontent.com/7022612/107517842-2e45c680-6ba6-11eb-9009-60e1d1c0e26b.png)

any ideas what can be causing this?

**Comment by lentinj** [comment]
Hrm, the peaks are definitely at 40/60/80/100/120 aren't they? That's definitely a clue. 

My first guess would be that some step is aggregating the length buckets unnecessarily, which should be obvious by the model defining a transformation matrix (``_lgmatrix``). There are a lot more than I expected, but most are just throwing away the plus group, e.g. ``environment(ling_model)$model_data$ling_imm_cdist_ldist_lln_model_lgmatrix``, or aggregating a length range into one bucket, e.g. ``environment(ling_model)$model_data$ling_mat_cdist_si_igfs_si2a_model_lgmatrix``. I've not looked exhaustively but I don't think this is it.

My second guess would be that renewal data itself is peaky, and is being preserved through the model. You could have reports on ``ling_imm__renewalnum`` to check this:

```
g3a_report_stock(imm_report,ling_imm, ~stock_ss(ling_imm__renewalnum))
g3a_report_stock(imm_report,ling_imm, ~stock_ss(ling_imm__renewalwgt))
```

...Initialconditions doesn't have a convenient variable to pull out the fish it added, but OTOH it's basically the value of the first step anyway.

**Comment by lentinj** [comment]
If you send me the parameters / update ``setup.R`` I can have a poke around further.

**Comment by bthe** [comment]
Nothing particularly striking from the recruitment:

![image](https://user-images.githubusercontent.com/7022612/107616074-3acd2c00-6c45-11eb-8caf-2b6f63b3c5f5.png)

Other than of course the really bad initial size distribution.. If I change the minimum size to 4 cm, thing start to improve a bit but the jaggedness remains:

![image](https://user-images.githubusercontent.com/7022612/107619422-0fe5d680-6c4b-11eb-94ef-74039efe8958.png)

So I guess this is related to the initial ldist. My current hypothesis is that the beta-binomial function is not doing what is supposed to as the beta parameter is optimised to 0.

**Comment by bthe** [comment]
The jagged can be blamed on an improper definition of the beta parameter, the model produces a lot smoother output now: 
![image](https://user-images.githubusercontent.com/7022612/107626739-247b9c00-6c56-11eb-965c-68eea35ead6d.png)

Mind you that the model is doing pretty weird things, but we are slowly but surely getting there:)
