### ISSUE TITLE
Remove sparseMatrix support, Matrix dependency

### ISSUE THREAD

**Issue by lentinj** [gadget-framework/gadget3#121]
We depend on [Matrix](https://cran.r-project.org/package=Matrix) for an R equivalent sparseMatrix support.

However, this has not been used for a long time, is not tested, and thus invariably broken.

Whilst it sounds useful, IIRC the performance hit wasn't worth it.

**Comment by bthe** [comment]
Sounds reasonable to me. I'm not even sure where sparse matrices would be useful, unless we are dealing with huge datasets.
