### ISSUE TITLE
g3a_report_detail error

### ISSUE THREAD

**Issue by MikkoVihtakari** [gadget-framework/gadget3#125]
Apologies for possibly not helpful bug report...When I run our [Greenland halibut model short-term projetions](https://github.com/DeepWaterIMR/nea-ghl-gadget/blob/master/14%20short-term%20projections.R) using the GitHub version of gadget3, I get:

```r
proj_actions <- c(proj_actions,
+                   list(gadget3::g3a_report_detail(proj_actions, run_f = ~TRUE)))
Error in g3a_report_history(actions = actions, var_re = c("__renewalnum$",  : 
  Don't know how to add history to ghl_female_imm__predby_fleet_stock: NULL
```

The code works without problems using the CRAN version of gadget3. Perhaps someone can guess where the error is given the recent changes.

**Comment by MikkoVihtakari** [comment]
Thanks Jamie. I thought I updated g3experiments. I'll check later.

**Comment by bthe** [comment]
> (also, I'm guessing `g3a_predate_catchability_hockeyfleet` isn't really an experiment any more)

yes, the code for the function is however still a bit messy, might be worthwhile to kick the tires a bit before it is included in g3 proper.
