### ISSUE TITLE
Integrated reporting

### ISSUE THREAD

**Issue by lentinj** [gadget-framework/gadget3#131]
(@bthe, @willbutler42 continuing from e-mail thread, to not bore Pamela further)

I think I've worked out a way forward.

#. Make existing report_all functionality optional, a reporting parameter to ``g3_to_tmb`` / ``g3_to_r`` that's can be all, detail, etc.
#. ``do_reporting`` DATA variable that can set the time dimension of detail arrays to 0 when unused, and disable the ``REPORT`` mechanism.
#. Use TMB ``DATA_UPDATE()`` to turn reporting back on inside our already-wrapped version of ``obj.fn$report``, this comes with warnings about messing up the tape, but in our case it's a good thing since we then hide the reporting from the tape as a by-product

So end result I think would be ``g3_to_tmb(report = g3a_report_detail(...))``, and then ``obj.fn$report()`` would only produce what comes out of g3a_report_detail. There'd no longer be a need for g3a_report_detail shenanigans in g3_fit.

**Comment by bthe** [comment]
Sounds good, and would certainly be more intuitive for new users.

**Comment by willbutler42** [comment]
Agree, this does sound like a good solution

**Comment by lentinj** [comment]
@willbutler42 if you've got a chance do you want have a play with https://github.com/gadget-framework/gadget3/commit/a4ceb61bee46c14abfe2ea86665fff40d84913e0?

With it you do ``g3a_report_detail(run_f = quote( reporting_enabled > 0 ))``, which will be 0 unless you're calling ``$report()``, so the reporting should be hidden from the tape & automatically disabled when optimising.

If this works & doesn't result in undue performance problems, we can start adding reporting by default.

**Comment by willbutler42** [comment]
Ace, will test this out, though you'll have to bear with me until next week due to teaching commitments the next few days

**Comment by willbutler42** [comment]
Just tested this out and encountered a small improvement in optimisation time and zero performance problems :)

**Comment by lentinj** [comment]
Ace, so looks like this will all work out. The only thing I'm currently unsure of is the interface.

We can either have a standard lump of code to copy-paste, say:

```{r}
g3_to_tmb( c(actions, list( g3a_report_detail(actions) )) )
```

Or we can pass in a function, so it happens by default:

```{r}
g3_to_tmb <- function( ... report_action = gadget3::g3a_report_detail, ...)

g3_to_tmb( actions )
```

The major downside of this is there's no way to supply arguments, and isn't very flexible long-term (what if we want 2 separate reporting functions? Do we need an extra argument for other types of last-minute actions?)

Another option is having a concept of action list "modifiers", to simplify the syntax of the first example, so you could end up with something like:

```{r}
g3_to_tmb( actions |> g3m_report_detail() )

# ... or, more enthusiastically:
g3_to_tmb( actions |> g3m_bounds_penalty() |> g3m_report_detail() |> g3m_trace_nan() )
```

Where ``g3m_report_detail()`` is ``g3a_report_detail()`` but concatenating it's actions on the end of the list. I've yo-yo-ed a bit, but I think I'm settling on the final option, and the cleaner interface makes up for having to specify what's essentially a default. Any thoughts?

**Comment by lentinj** [comment]
Actually, whilst action-list modifiers are fun, a more fundamental question is why we need to do this later, instead of adding report parameters like the likelihood components have:

```{r}
# NB: In reality the report parameter would default to TRUE, since there's little reason to turn it off
actions_fish <- list(
      . . .
  g3a_renewal_normalparam(fish,
    run_step = 2, report = TRUE),
  g3a_age(fish, report = TRUE),
  NULL)

actions_f_surv <- list(
  g3a_predate_fleet(
    f_surv,
    list(fish),
    suitabilities = g3_suitability_exponentiall50(),
    catchability_f = g3a_predate_catchability_totalfleet(
      g3_timeareadata("landings_f_surv", landings_f_surv, "weight", areas = area_names))),
  report = TRUE)
```

The main question is then where to hang the abundance reporting. In ``g3a_age`` seems a bit wrong, but hanging it off renewal would mean we'd have to implement abundance reporting in both renewal and spawning.

**Comment by lentinj** [comment]
Having thought about this somewhat, whilst the latter would be less of a hack internally, it's not very user-friendly. You can see from the existing models that having a single reporting on/off is more useful than lots of little reporting switches. Doing something like ``g3_to_tmb( actions |> g3m_report_detail() )`` is much neater from a user point of view I think.

The ``wip-integrated-reporting`` branch now doesn't report every variable by default any more, instead we add variables to the report that we think we need. @willbutler42 would you mind checking at some point that I haven't missed anything?

Another thing that would be nice to sort out now if we can, I'm a bit worried that the early reporting of abundance, vs. the late reporting of everything else, is a bit mystical. IIRC the main advantage of this is you get the initialconditions, yes? Maybe what we could do is extend the reporting period for abundance, so you have a "time 0" column which is early-reported, the rest late-reported.

Also any votes on the syntax to add the reporting to the model? Neither is harder than any other, but it'd be good to get right and not have to back it out.

**Comment by bthe** [comment]
I guess action modifiers are the way to go, but if you don't report everything by how would you go about defining what variables to report? I'm pretty sure I would always want the abundance and consumption reported. It could also be good idea to think about how one could define custom functions of stock variables (e.g. fishing mortality and SSB) to be able to estimate the uncertainty via adreport.

> Another thing that would be nice to sort out now if we can, I'm a bit worried that the early reporting of abundance, vs. the late reporting of everything else, is a bit mystical. IIRC the main advantage of this is you get the initialconditions, yes? Maybe what we could do is extend the reporting period for abundance, so you have a "time 0" column which is early-reported, the rest late-reported.

Yes, this is pretty much the reason for reporting abundance at the start but the abundance at the end of a timestep is obviously the same as the abundance at the begining of the next year. Might need to have a functions that can appropately change the year/step/age.

**Comment by lentinj** [comment]
> if you don't report everything by how would you go about defining what variables to report?

``g3a_report_detail()`` is just a call to ``g3a_report_history()`` with a pre-canned regex.

If you wanted to do your own, you could do ``actions |> g3m_report_history('__num$')`` to only get abundance.

> It could also be good idea to think about how one could define custom functions of stock variables (e.g. fishing mortality and SSB) to be able to estimate the uncertainty via adreport.

I think we covered this with ``g3a_report_stock()`` already.

**Comment by lentinj** [comment]
@willbutler42 I've been having lots of fun with the ``wip-integrated-reporting`` branch over the last few days.

* We don't report anything by default any more, so you have to add something like ``g3a_report_detail()``.
* TMB can now properly set the time dimension names for abundance reports (without g3_fit() would choke on the TMB reported output)
* ``g3l_bounds_penalty()`` doesn't hard code the bounds any more, and you don't have to give it a parameter template. We include the bounds as DATA attached to the TMB model, which we update when running ``g3_tmb_adfun``.

The upshot is that you can generate a model with:

```{r}
model_code <- g3_to_tmb(c(actions, list(
    g3l_bounds_penalty(actions),
    g3a_report_detail(actions) )))
```

...and the bounds in the parameter template should just work™, and ``obj.fn$report()`` should produce reports ready for feeding into ``g3_fit()``, which won't need to do any of the recompilation shenanigans. \o/

...in theory. I've flushed out most of the bugs but something is still missing from the report that's causing ``g3_fit()`` to produce nonsense. Any chance you could have a try and see if you can figure out what's missing? I can't spot it.

I've not committed the action modifier wrappers yet, so you can't do ``g3_to_tmb( actions |> g3m_report_detail() |> g3m_bounds_penalty() )``. They're trivial to do, but a sense of foreboding is stopping me doing it for now. I'll see if I can figure out why that might be at the weekend.

**Comment by willbutler42** [comment]
Great! 
Regarding the nonsense, I assume you are talking about a harvest rate of 0 when there are catches?? If so, I believe the culprit is here: https://github.com/gadget-framework/gadgetutils/blob/main/R/g3_fit.R#L85 - a rather clunky way of getting the step size to scale mortality

**Comment by lentinj** [comment]
Ah yes, it's the time step is "001" now, since I had to put the reporting before it. I've made a pull request to sort this out: https://github.com/gadget-framework/gadgetutils/pull/27

This isn't the end, but I think the error message has changed so hopefully things are improving :D

**Comment by lentinj** [comment]
Right, with the above commit the reports are similar enough that gadgetplots can do it's thing again. I still need to rework the vignettes to match what's now best practice, but hopefully everything is working now.

I think I'll leave the action modifiers; I think the main thing that's been bothering me about it is it's a fair bit of upheaval for a little bit of syntactic sugar, which will be copy-and-pasted most of the time anyway. And there's nothing stopping us doing it further down the road if we need to.

**Comment by willbutler42** [comment]
> Right, with the above commit the reports are similar enough that gadgetplots can do it's thing again. I still need to rework the vignettes to match what's now best practice, but hopefully everything is working now.
> 
> I think I'll leave the action modifiers; I think the main thing that's been bothering me about it is it's a fair bit of upheaval for a little bit of syntactic sugar, which will be copy-and-pasted most of the time anyway. And there's nothing stopping us doing it further down the road if we need to.

Fwiw, I just checked a model and can confirm its fit is now identical between the master and wip-integrated-reporting branches, that is each list element's dimensions and values are identical (only exception is the report_detail parameter in fit$params for the latter branch - which was expected)

**Comment by lentinj** [comment]
Thanks! I'll get this merged and consider it done (finally).

The ``report_detail`` parameter could eventually go entirely, but for now it keeps g3_fit working.
