### ISSUE TITLE
Predation - Otherfood equivalent

### ISSUE THREAD

**Issue by lentinj** [gadget-framework/gadget3#155]
@bthe / @willbutler42 / @vbartolino 

For #29, gadget2 has [OtherFood](https://gadget-framework.github.io/gadget2/userguide/chap-other.html#chap-other), we need something similar.

I'm thinking of a variation of initialconditions, say ``g3a_renewal_staticstock()``, that works identically to initialconditions but will run on every step rather than just the first one, throwing away any stock from previous step and repopulating.

Does this sound good? Will GoB need it?

**Comment by bthe** [comment]
This sounds good, and would allow you more flexibility, e.g. define length and/or based predation on otherfood. I think otherfood is always needed as you will need to balance the feeding equations with additional energy from other sources.

**Comment by vbartolino** [comment]
> I'm thinking of a variation of initialconditions, say g3a_renewal_staticstock(), that works identically to initialconditions but will run on every step rather than just the first one, throwing away any stock from previous step and repopulating.

my initial guess was that otherfood would have been implemented with something like `g3_timeareadata` but your suggestion is probably better as @bthe points out (ie, it would allow to define length...).

> Will GoB need it?

certainly it will have otherfood.

I assume it would be possible to have more than one otherfood component if wished, correct? In principle, if I find a reasonable time series of stickleback abundance, we could have two otherfood components, one reflecting stickleback and another generic for the rest

**Comment by lentinj** [comment]
I think this is largely done now. Otherfoods get defined like any other stock:

https://github.com/gadget-framework/gadget3/blob/a5d4f905d0d7f9f18453cac55f92f60ae0524942/tests/test-action_renewal-otherfood.R#L6-L8

...then for each, we add the otherfood action:

https://github.com/gadget-framework/gadget3/blob/a5d4f905d0d7f9f18453cac55f92f60ae0524942/tests/test-action_renewal-otherfood.R#L28-L34

* if using ``g3a_otherfood_normalcv``(), the stock has to have (an) age as well as length, otherwise the vonB renewal formulae fall over. I'm assuming this is fine though, and trying to special-case this is more trouble than it's worth.
* Do we want to parametrise ``g3a_otherfood``() by default, with options set to something like the above? I'm guessing in general that's what you want.

**Comment by lentinj** [comment]
Also, the point I was supposed to make with the above. ``ifmissing = 0`` is needed because our order of actions is (initialconditions) / (early_report) / (stop model run). So we run g3a_otherfood once after the model has finished.

This knot could probably do with unpicking, but having a value for other years is very likely for projections anyway.

**Comment by lentinj** [comment]
The above makes ``g3a_otherfood()`` a bit nicer to work with.

* https://github.com/gadget-framework/gadget3/commit/306b0da624ed51376bb6617f3b044d9cbd8a081d means we don't have to specify ``ifmissing = 0`` (although some kind of ifmissing will be required for projections eventually).
* https://github.com/gadget-framework/gadget3/commit/1a256fd2f71a9cf635da014e0552bfb6ce19fe88 means the ``offset = quote(0 * other_wgt__midlen)`` hack is no longer necessary, we add it internally if required.
* https://github.com/gadget-framework/gadget3/commit/c26d10c5205a2bd0065f2f7fb5edf8637ce2ace9 sets some parametrisation by default. Open to suggestions though on better defaults.
