### ISSUE TITLE
Combining lists of actions & single actions results in a mess

### ISSUE THREAD

**Issue by lentinj** [gadget-framework/gadget3#157]
``c(g3a_x(),  list(g3a_x()))`` results in a silent mess. Either:

* We should be more flexible in ``g3_collate()``, and not worry about it
* Add classes so we can add ``c.g3_action``, catch this and complain.

**Comment by vbartolino** [comment]
in the 3 species model https://github.com/vbartolino/g3_GoB/blob/main/rin_ven_her_g3/gadget3/02-setup/setup.R that seems to work. Is that a special case or I was overoptimistic about that run?

```
## collate the seal actions
actions_rin <- c(
  stock_actions,
  fleet_actions,
  likelihood_actions,
  time_actions,
  NULL
)
...
## collate the vendace actions
actions_ven <- c(
  stock_actions,
  fleet_actions,
  likelihood_actions,
  time_actions,
  NULL
)
...
## collate both actions together
actions <- c(actions_rin,
             actions_ven,
             NULL)
```
