### ISSUE TITLE
Feeding alpha/beta back to gadget_fit

### ISSUE THREAD

**Issue by lentinj** [gadget-framework/gadget3#17]
A generic gadget_fit or similar tool needs to know what parameters ``g3l_distribution_surveyindices_log`` was passed (for example, although this is a generic problem), without the user having to feed them in twice. Broadly this means doing one of:

* We provide a mechanism to store the input formula and re-evaluate them separately, using similar mechanisms to eval'ing ``g3_param_table`` arguments.
* We add the used value into the report, dig it out from there.

Making such high-level assumptions about the structure of the model is a bit fraught with peril, somewhat akin to treating LaTeX documents as using a high-level markup language. However if the value of ``alpha`` isn't an easy question (e.g. because it's dependent on something time varying), then it'll go wrong regardless of approach.

**Comment by bthe** [comment]
Alternatively, we could store the processed output, i.e store `predicted = exp(alpha + beta*log(model))`.

**Comment by lentinj** [comment]
To add to the complication here, ``alpha`` and ``beta`` now could be calculated values, so assuming there's a parameter isn't going to work either.

I think the solution lies in 2 things that have been rattling around my workspace.

* If a formula relies on a definition, put that definition in a more appropriate place (e.g. in the stock loop, the step), not just at the very top of the model. This would be a dramatic improvement in how customisable formulas are and how readable the resultant code is.
* A better means to define what should be reported. ``g3_report()`` is a quick hack, and encourages it's use within a loop, which is entirely wrong (since we constantly reset the output value).

Together would let surveyindices output it's own ``__alpha`` and ``__beta`` reports. I just have to work out what I mean by the second point first :)

**Comment by lentinj** [comment]
* Reporting everything available sounds like the right approach, rather than faff around configuring.

**Comment by lentinj** [comment]
This is now done. You'll get a ``cdist_{nll_name}_model__params`` report for any surveyindices likelihood comparison, with either the fixed values or the results of the linear regression.
