### ISSUE TITLE
Random effects not reported properly

### ISSUE THREAD

**Issue by bthe** [gadget-framework/gadget3#195]
Been banging my head against the wall to try to get sensible output from the random effects estimation procedure and for some reason I always get the initial values for those parameters, not the optimised ones. 

My guess is that this has to do with `g3_optim` not doing the right thing roughly here: https://github.com/gadget-framework/gadgetutils/blob/main/R/g3_optim.R#L153C4-L153C51

I assume what we want here is instead of `obj.fn$par` we want `obj.fn$env$last.par`?

**Comment by lentinj** [comment]
Yup, ``obj.fn$par`` will always be the initial parameters. ``obj.fn$env$last.par`` will be the parameters used in the last run (assuming the last one was the best one), ``fit_opt$par`` is probably the best choice, i.e. the output of ``optim()``.

But that said, I can't see a stray ``obj_fun$par`` in g3_optim(). However, if the optimisation fails, then fit_opt is filled with the initial parameters. Maybe this is what you're looking at? https://github.com/gadget-framework/gadgetutils/blob/main/R/g3_optim.R#L117-L121

Also worth noting that TMB tell you not to trust the default values when using ``obj.fn$report()``, and to explicitly give it a ``par`` to work with. This is another likely source of problems.

**Comment by bthe** [comment]
Hmm.. looking at the code in `g3_optim` I see that it only pulls out the results from `optim` (see https://github.com/gadget-framework/gadgetutils/blob/main/R/g3_optim.R#L102-L109 ) but does not go back to the environment of `obj_fun` to pull out the random effects as `optim` does not report those values . Am I missing something obvious?

**Comment by lentinj** [comment]
Oh, good point. Random effects are essentially fixed as far as optim is concerned. So yes, they fall back to the initial parameters.

Given that, we should be using ``obj$env$last.par.best`` instead.

There's also ``obj$env$parList`` for converting back to a list of arguments. The code we want is somewhere in this lump: https://github.com/kaskr/adcomp/blob/943a9ecf02838381c1d7094441b2880490cae53f/TMB/R/checker.R#L75-L97

**Comment by lentinj** [comment]
So, if I understand the above, it's:

```r
parfull <- obj$env$last.par.best
r <- obj$env$random
if( any(r) ) par <- parfull[-r] else par <- parfull

obj$env$parList(par, par = parfull)
```

...i.e. ``par`` is the best parameters ignoring random effects, and ``parfull`` includes random effects. Why ``parList`` needs both, I've no idea atm.

**Comment by bthe** [comment]
I think the solution is even simpler than that. This

```
obj$env$last.par.best
```

seems to give us me all the model parameters, including the random effects.

**Comment by lentinj** [comment]
That should give you the parameter vector, but at some point you need the full parameters object you put in, this is what ``obj$env$parList`` / ``gadget3::g3_tmb_relist`` try and do.

Having a quick glance, ``gadget3::g3_tmb_relist(params, obj_fun$env$last.par.best)`` should work out the random parameters are included and do the right thing.

Ideally we switch to using ``parList`` at some point, given it's TMB way of doing it, but I don't think it matters too much.
