### ISSUE TITLE
weightJones: max vs realised consumption

### ISSUE THREAD

**Issue by vbartolino** [gadget-framework/gadget3#198]
as I understand the code, `g3a_grow_weight_weightjones` points to the maximum consumption while I think it would be more useful to point to the realised consumption. Under food limitation the two would be different which is the essence and reason for using weight Jones. Do you agree?

https://github.com/gadget-framework/gadget3/blob/d24d44cb5f00ef542ecfaf2ae97a14331970cb39/R/action_grow.R#L122

**Comment by lentinj** [comment]
This isn't the first time I've looked into this:

https://github.com/gadget-framework/gadget2/commit/91dc09b8346c478f97d48065fe07d89eacab635f

The conclusion of that is WeightJones' $C$ is $M \psi$. But, as you say, the code above doesn't seem to have got the memo.

This is probably a case of changing ``max_consumption`` to ``max_consumption * stock_ss(stock__feedinglevel)``. I'll give this a go.
