### ISSUE TITLE
Complete fleet modelling

### ISSUE THREAD

**Issue by lentinj** [gadget-framework/gadget3#24]
Currently there is only ``totalfleet`` implemented, loosen seams so a formula can be provided that can emulate ``linearfleet`` and ``effortfleet``, similar to likelihood. The worth of ``numberfleet`` is debatable, but still used often.

### Examples of gadget2 models to integration-test against

* https://github.com/gadget-framework/gadget-course/blob/master/projections.Rmd#L77
  * Based on ``linearfleet``: https://github.com/gadget-framework/rgadget/blob/e45306ea9fb610954d6e5a577f624867d59f406c/R/gadget_forward.R#L374

**Comment by lentinj** [comment]
This for the most part is pretty easy. The above refactors the totalfleet part into a ``g3a_predate_catchability_totalfleet``, and I've got implementations of the others awaiting a bit more testing.

Obviously the thorn here is ``quotafleet``, which obviously isn't going to produce anything differentiable. We could do something kinda similar with ``logspace_add`` and flip between 2 values, but that's not exactly a fully-featured drop-in replacement...

**Comment by bthe** [comment]
> Obviously the thorn here is ``quotafleet``, which obviously isn't going to produce anything differentiable. We could do something kinda similar with ``logspace_add`` and flip between 2 values, but that's not exactly a fully-featured drop-in replacement...

I don't think that differentiability matters much in this context. The quota fleet was probably never meant to be used when optimising, rather in projections.

**Comment by lentinj** [comment]
Okay, I think that finishes these off, ``quotafleet`` results in a big if statement, which if you're not optimising isn't a problem.

Could probably refactor these a bit more to make the component parts more available, but can do so at a later date when they look like they'd be useful.

**Comment by lentinj** [comment]
* Expose g3_per_stock() rather than hiding it away in effortfleet
