### ISSUE TITLE
Spawning

### ISSUE THREAD

**Issue by lentinj** [gadget-framework/gadget3#25]
Implement ``spawning`` as per gadget2: https://gadget-framework.github.io/gadget2/userguide/chap-stock.html#sec:stockspawn

### Examples of gadget2 models to integration-test against

* https://github.com/gadget-framework/gadget-course/blob/master/minke_whale_model.Rmd#L171
* https://github.com/gadget-framework/gadget-course/blob/master/stock_interactions.Rmd#L81

**Comment by lentinj** [comment]
@bthe Spawing's ``onlyparent`` mode, why? AFAICS it's just another mortality with an extra weight loss function. You don't even get to know the proportion that "spawned" via. the printer.

Unless proven otherwise, I'll assume a recruitment function and ignore ``onlyparent``. We could add weight loss to ``g3a_naturalmortality()`` easily enough.

**Comment by bthe** [comment]
I would proceed as you suggest. 

This function is kind of weird,the  thing is that is different from standard natural mortality as it would allow you todo length based mortality/weight loss (is that implemented somewhere in g3?). It sort of makes sense to do this here in gadget2 but not so much in g3 as it is probably neater to do this when you define mortality.

**Comment by lentinj** [comment]
> length based mortality/weight loss (is that implemented somewhere in g3?)

Yes, that's not an issue in g3. It should be possible to have multiple mortality actions, but don't quote me on that.

**Comment by lentinj** [comment]
I've got something that can do spawning, pretty much mimicing g2 now.

As well as not considering the onlyparent case (which would be pretty easy actually), I've done some other deviations from how g2 spawning works, which I think make sense:

* With g2, spawning is calculated based on total (spawning) biomass for an area. I've simplified this to just have one total (spawning) biomass for spawning operation, but allow multiple spawning operations.
    * For no/single area models, it's irrelevant anyway
    * For multi-area models, it allows you to have differently defined spawning areas (e.g. one spawns earlier in the year than the other).
    * The hard part would be implementing a multi-area model with spawning everywhere---well, without repeating g3a_spawn() for each area.
* With g2, the normal distribution is generated for a pseudo stock (the union of the output stocks), these are then converted into each output stock. g3, the normal distribution is generated for each output stock. I'm pretty sure this is an improvement, and most of the time (1 output stock) is a non-issue anyway.

Also, the g2 manual says:

> The total number of recruits given by the spawning process is added to the youngest age group of the spawned stock at the start of the following timestep.

As far as I can see, this is lies. They get added along with other renewal stocks soon afterwards.

**Comment by lentinj** [comment]
The main problem I know of with the above is it's not very accurate vs. g2 if spawning mortality is non-zero. But I'm not sure where this is coming from atm, it's seemingly not a problem with mortality itself, but an ordering problem or exacerbating some other problem.

I'll come back to it after considering any CKMR changes.

**Comment by lentinj** [comment]
re: Spawning being based on (an area's) total biomass. This seems a bit rubbish given in CKMR we want to consider how many parents there are for a given age. Obviously we can just assume an even spread of spawning over ages/lengths, but feels like we could be doing something better.

**Comment by bthe** [comment]
> re: Spawning being based on (an area's) total biomass. This seems a bit rubbish given in CKMR we want to consider how many parents there are for a given age. Obviously we can just assume an even spread of spawning over ages/lengths, but feels like we could be doing something better.

And would this not be accomplished via the spawn selection (suitability) functions?

**Comment by lentinj** [comment]
For deciding the proportion of adults spawning, yes.

The problem is with the recruitment functions, e.g. ricker. Currently none of the recruitment functions will tell us the number of offspring for an age group, so we have to assume somewhere that it's evenly spread, which doesn't feel like a great assumption.

OTOH, considering each age group in isolation wouldn't be a great move either. Most species you're likely to model aren't going to stick rigidly to their age groups when spawning.

**Comment by bthe** [comment]
Yes, this leads us to size based fecundity. My first thoughts are that the default option should be to assign the number of recruits by biomass of each parent age-group (but I think abundace is something we would want pretty soon as well). But the general case I think using selection functions to assign recruits to parent age group would be flexible enough.

**Comment by lentinj** [comment]
* Get rid of ``spawn_length_*``, use selectivity
* Recruitiuitutment spelling
* Expose extra ricker-like functions, but steer clear of baleen for now (neither formula or implementation in gadget2 is quite right)

**Comment by bthe** [comment]
Yes, for the most part they are the same (although the naming in g2 might have been more consistent with exponential <-> expl50, and that was also a wrong name as this actually a logistic curve but I digress). Things get a bit hairy when you add predator length into the mix, but that can be fixed with, as you say, clever defaults.

**Comment by lentinj** [comment]
Yeah, I somehow didn't notice ``exponentiall50`` just below :) Ah well.

This is done now. ``pred_stock`` isn't really a problem, if you don't have a predator then you shouldn't be including formulas that use it. ``prey_stock`` is more thorny, since calling the spawning parents ``prey_stock`` to use the selectivity functions is kinda dumb.

So I've hacked away and renamed ``prey_stock`` to ``stock``, which makes the predation action code not as readable annoyingly, but I don't think there's any other obvious choices.

**Comment by lentinj** [comment]
Now ``stock__spawnprop`` is generated, for use in ``gadget.fit``.
