### ISSUE TITLE
error with demo function

### ISSUE THREAD

**Issue by mmrinconh** [gadget-framework/gadget3#3]
Hi, I just made the following:
`install_github("lentinj/gadget3")
library(gadget3)
demo("ling", package = "gadget3")`

and I got:
`Error in demo("ling", package = "gadget3") : 
  No demo found for topic ‘ling’`
Any help would be appreciated! Thanks!

**Comment by lentinj** [comment]
Sorry, we moved it into here, where it's set up in multiple files more like Bjarki's other models: https://github.com/lentinj/gadget3/blob/master/demo-ling/setup.R although it's still having problems currently...
