### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by lentinj** [gadget-framework/gadget3#31]
The migration matrix in gadget2 is a bit broken, and far to easy to magic fish in/out of existence.

We should take a more gadget3 approach of describing processes with a function, and allow multiple migration processes 

### Rough implementation

* Iterate over stock, and ``for(dest_area in seq_along(stock__areas)``
* Have a run_f as usual for doing things like ``cur_step == 2 && dest_area == 1``.
* Add an ``if (area != dest__area)``, to save having to add it to run_f each time.
* Accept a proportion (optionally by number/weight) to move for current stock_area to dest_area.

Possibly have an optional ``dest_area`` argument that simplifies the case where you only want to consider what's moving to a single area, e.g.  ``dest_area = areas[['spawning_grounds']]``.

Make sure proportions are normalised before actual movement happens.

**Comment by lentinj** [comment]
Question time for @bthe:

The normalisation function isn't necessarily obvious. You can make sure they sum to 1 by dividing by the total, or you can make up the difference by setting the proportion that don't move (I'm guessing the common case you want to say things like "In spring, 40% move over here", having to also state that the rest stay put is a bit boring for the modeller and an avenue for bugs).

What sort of things would you expect to be reportable? The easiest thing to do is to generate proportions for a single length group at a time, but then there's nothing useful to report. OTOH, storing a full stock array for each area containing the proportions that migrated seems rather wasteful and ungainly to use the other end. Maybe a "proportion that migrated" array so you can at least see when migration is happening?

**Comment by bthe** [comment]
> The normalisation function isn't necessarily obvious. You can make sure they sum to 1 by dividing by the total, or you can make up the difference by setting the proportion that don't move (I'm guessing the common case you want to say things like "In spring, 40% move over here", having to also state that the rest stay put is a bit boring for the modeller and an avenue for bugs).

Just to have the notation set up, when you have for each stock a migration matrix `M` where `m_ij` represents the probability of going from area `i` to `j`. The entries in `M` are subject to `0<m_ij` and `sum_j m_ij = 1`. The former requirement is easy to satisfy by squaring the parameter, while you need to normalise the entries in the matrix to satisfy the second. I guess how this would work out is that the user would supply migration parameters `p_ij` and then `m_ij = p_ij^2/sum_j p_ij^2`.

And then if the user does not supply a parameter for `p_ij` then it could simply be automatically generated. If this is set up this way guess this could essentially allow the user to specify where the fish does not go and then let the model take care of the rest. 

> What sort of things would you expect to be reportable? The easiest thing to do is to generate proportions for a single length group at a time, but then there's nothing useful to report. OTOH, storing a full stock array for each area containing the proportions that migrated seems rather wasteful and ungainly to use the other end. Maybe a "proportion that migrated" array so you can at least see when migration is happening?

Yes, I think the interesting bits would be the entries of `M`, the migration matrix described above. Everything else can be inferred from that and the abundance.  

Then there is the interface to all this. Are you thinking about copying the gadget2 interface, i.e. define a set of migration matricies and then supply a list indicating the steps when the apply? This setup always felt a bit weird, as I would think you could simplify it a bit with time variables.

**Comment by lentinj** [comment]
Just after I posted the above I realised we could auto-fill NA gaps to solve the "and the rest" problem.

Defining a migration matrix directly has 2 problems:

* You couldn't vary the migration based on age / length, it'd be fixed for that timestep to make sense
* There's a limit to how much matrix juggling you can do within a formula, I suspect you'd just end up supplying a bunch of matrices and choosing between them.

...but OTOH maybe the former problem isn't really an issue, and you'd never want to do that?

The latter can be managed by supplying a formula, as below.

> The entries in M are subject to 0<m_ij

Which presumably will only happen if you let the optimiser loose on some part of the matrix, the user's wouldn't directly do that (would they? :P).

> Then there is the interface to all this.

I think my preferred interface atm is something like ``run_f = ~cur_step == 2, migrate_f = ~if (dest_area == 2) 0.6 else NA``. Where the former ``run_f`` makes sure this only ever happens in spring, the latter ``migrate_f`` is used to build the matrix given area/dest_area, where ``NA`` values will be a filled in from ~the identity matrix. I guess this is probably more similar to the latter of the gadget2 interfaces.

You could have a separate action to define a fixed matrix instead of a ``migrate_f``, but I'm not hugely convinced of the value.

**Comment by bthe** [comment]
> .You couldn't vary the migration based on age / length, it'd be fixed for that timestep to make sense

Not sure if that is big a problem, but you could borrow the interface from spawning by specifying a length selection function on top of the migration matrix. 

> Which presumably will only happen if you let the optimiser loose on some part of the matrix 

Yes, pretty much

> ..  the user's wouldn't directly do that (would they? :P).

There is probably a meme about this somewhere;) 

> `run_f = ~cur_step == 2, migrate_f = ~if (dest_area == 2) 0.6 else NA`

The interface sounds fine with me, I wonder what would happen here in the 3 area case, as I read this `NA`'s are all filled with the same constant, so if you want to have separate migrations to area 1 and 3 then you would need to specify that explicitly.

**Comment by lentinj** [comment]
> specifying a length selection function on top of the migration matrix.

That's a neat idea. Let's do that.

> as I read this NA's are all filled with the same constant
 
The theory is NA values are filled with ``if (area != dest_area) 1 - sum(row) else 0``, rather than just a constant. However now having tried to implement it I'm not sure it's a great idea.

The above isn't quite right, since 2 --> 2 would be assigned 0.6. It'd have to be ``if (area != dest_area && dest_area == 2) 0.6 else NA``, which is getting wordier. Having to worry about the go-nowhere diagonal isn't helpful.

I think I've changed my mind to ``if (dest_area == 2) 0.6 else 0``, and we always recalculate the diagonal to balance out the movement. So it's not possible to state the proportion of fish that stay in an area, but it wouldn't be possible to implement anything useful (e.g. dispersal) like this anyway.

With 3 areas I could do ``if (dest_area == 2) 0.5 else if (area == 2 && dest_area == 1) 0.2 else if (area ==3 && dest_area == 1) 0.4 else 0`` and get:-

```
    1   2   3
1   - 0.5   0
2 0.2   -   0
3 0.4 0.5   -
```

... and, after filling in the gaps...

```
    1   2   3
1 0.5 0.5   0
2 0.2 0.8   0
3 0.4 0.5 0.1
```

**Comment by lentinj** [comment]
Okay, I think the above gets something going. Have a look at the test for an example for how to use it. Still not convinced by the normalisation function. Possibly need a "human" and "optimiser" version.

**Comment by lentinj** [comment]
There's another flaw in the implementation. If you specify a migration formula with 1 -> 2 and 2 -> 3, then some will migrate 1 -> 3. Not convinced it's a huge problem in reality mind.
