### ISSUE TITLE
Error on stock__suit_fleet with g3a_predate_totalfleet

### ISSUE THREAD

**Issue by pfrater** [gadget-framework/gadget3#33]
In trying to create a very simple model with a single stock and single fleet (following the example from `demo-ling`), I come across the following error when running the function resulting from g3_to_r:

    Error in stock__suit_fleet[, stock__area_idx, stock__age_idx] <- NULL : 
     number of items to replace is not a multiple of replacement length

I've narrowed it down to stemming from `f_substitute` within `g3a_predate_totalfleet`. The object `suit_f` cannot be found as an argument when that function is called (see R/action_predate.Rf L45-62). The argument is assigned as `suitabilities[[prey_stock$name]]`, which apparently cannot be found. Any thoughts on what I might be doing wrong?

**Comment by lentinj** [comment]
Sorry, I should have made that error more obvious. The above does so.

As for the actual error, my best guess is a mismatch between variable and stock names. Say you have something like:

```
ling_imm_the_var <-
  g3_stock('ling_imm_the_stock_name', seq(4, 156, 4)) %>%
  g3s_livesonareas(areas[c('1')]) %>%
  g3s_age(3, 10)
```

...you need to refer to ``ling_imm_the_stock_name``, not ``ling_imm_the_var``.
