### ISSUE TITLE
(regular) Tagging

### ISSUE THREAD

**Issue by lentinj** [gadget-framework/gadget3#36]
Think this is worth having a separate ticket to #30.

"regular" tag/recapture experiment will report individuals that were captured first time around and second time around. Need to consider the probability that an individual survives through all processes from time of capture event, to being around (and being caught) in recapture event. Some extra events would need to be added too, e.g. tag shedding (tags drop off) and tag mortality (fish don't survive the tagging operation).

- [ ] Convert the tagging fleet's catch back to individuals, record both catch and overall numbers
- [ ] Apply mortality, re-insert back into relevant stocks
- [ ] Next time around, compare proportion of prev.catch vs overall to catch amounts, deriving proportion that should be tagged.
- [ ] Compare (same as CKMR, but how) to proportion tagged from observation data

* If we don't need to consider recapturing a fish twice, we can get away without storing history like we do with CKMR
* Do we expect to compare size / age structure of recaptured fish? In theory a regular likelihood component will keep the catch structure in-line. gadget2 did by size, and then has *RecStatistics* to inspect length-at-age further.

**Comment by lentinj** [comment]
* Recapture is done by commercial fleets
* May not have reliable size information for what you've tagged (e.g. shooting something at a whale, not pulling out measuring and putting back in), but oddly-shaped selectivity curves for a fleet would emulate this.
* Need to think about movement from start.

**Comment by lentinj** [comment]
@bthe If the tag-release action has an ``output_tags`` and ``output_ratios`` option which work like the ``output_stocks`` and ``output_ratios`` option, is a separate formula for tag shedding really necessary, given "not tagged" is an output tag?

It would mean you couldn't do things like vary tag shedding based on age, but not sure how annoying that would be in reality.

**Comment by bthe** [comment]
I have not seen cases where you would have age specific tag shedding so I don't think that is a big limitation. I guess with tag shedding is that you want the shedding to occur according to the formula
```
N_{t+1} = N_t * exp(-p_t) 
```
where `N_t` is the number remaining in the tagged population at time t and `p_t` is the proportion shed at time t. So how would you set this up with the options you are describing?

**Comment by lentinj** [comment]
I was thinking about what happens at the initial tag-release step, releasing the fish caught by a fleet after assigning a tag. Per-step tag-shedding will be basically naturalmortality-but-with-tags (pretty much as you state).

I guess the question is better phrased as how flexible does the tag assignment for an individual release need to be. Would you choose a tag based on length (e.g.)? Would you assume that 20% fall off immediately, on top of of general tag shedding? Or is this unnecessary logic and 1 harvest == 1 tag?

**Comment by lentinj** [comment]
Okay, I've sketched out a bunch of functions to implement tagging in the above commit.

* ``g3s_tag``: Add an extra "tag" dimension to the stock, with any number of tags + untagged
* ``g3a_tag_release``: Take the output of fleet(s), add them back (after mortality) to the specified tag(s)
* ``g3a_tag_shedding``: naturalmortality, but move back to untagged "tag".
* A note to add tag support to ``likelihood_data``, at which point we can use ``g3l_distribution`` with catch data.

...I think this is approximately what we need. The plan of tracking proportions above (like CKMR) doesn't seem worth it here if we need to take movement into account.

Feel free to nosey & comment if the code makes sense. There's a bunch of questions to think about, one of which is where the above fits into the order of calculations.

**Comment by bthe** [comment]
> Would you choose a tag based on length (e.g.)? 

Yes, I would either assume that the length is known or selected using a selection function. I think other properties are harder to assume known.

> Would you assume that 20% fall off immediately, on top of of general tag shedding? Or is this unnecessary logic and 1 harvest == 1 tag

Immediate tagging mortality as you describe it is pretty likely. Although this could be achieved with timevarying mortality I think that you would want to add it explicitly.
