### ISSUE TITLE
Allow gadget.fit to add it's own reports

### ISSUE THREAD

**Issue by lentinj** [gadget-framework/gadget3#37]
``gadget.fit`` needs to know history of ``__suit`` (e.g. ``__num`` also occurs), shouldn't be reliant on users making an appropriate report.

Possibly:

* Annotate tmb version with equivalent R function of model
* Helper to modify R model and insert required reports
* re-run with optimized parameters, and get reported values.

**Comment by bthe** [comment]
There is also a food for thought that in `gadget_forward`,  one would like to extend time, add spawning to a stock and define new fleets. In this scenario you would want to be able to call random number generators (e.g.`rnorm` and the like) and possibly other R functions.

**Comment by lentinj** [comment]
> one would like to extend time

I think the solution here would be to add support for projection into ``g3a_time`` with a ``project_years = g3_param('project_years', optimize = FALSE)`` parameter. Fleet definitions could use a ``is_projecting`` or  something to tell whether to use provided data or something like quotafleet.

> add spawning to a stock and define new fleets.

Why add spawning, out of interest? I think this renders the "post-collation single formula" comment above pointless though, since adding extra predation would be way too complex.

> In this scenario you would want to be able to call random number generators (e.g.rnorm and the like) and possibly other R functions.

So long as they don't end up in code that goes through ``g3_to_tmb`` that's fine.

**Comment by bthe** [comment]
For fleets data/parameters for the projections would need to be supplied. In most cases you would work with `quotafleet` but in principle you could use any type of fleet. 

>     Why add spawning, out of interest? 

You often estimate recruitment as a free parameter (i.e. independent of stock size) while in projections you want recruitment to react to changes in stock size so spawning is only defined in the period of the forecast. An example of this is shown in https://gadget-framework.github.io/gadget-course/projections-using-rgadget.html

**Comment by lentinj** [comment]
- [ ] Add source list of actions as an attribute to the output of ``g3_to_*``, this means you can add to the model exactly as you would normally.
- [ ] Add ``project_years`` as above to ``g3a_time``, along with a ``cur_is_projecting`` variable.

Me and @bthe also talked about a quota decision action to use in fleets, not to be done yet but scrawled some notes here: https://github.com/gadget-framework/gadget3/issues/43 (feel free to comment).

**Comment by lentinj** [comment]
The above adds the actions as an attribute, so it's easy to fish out the list of actions, add reports and rebuild.

You could also build a ``gadget_update`` using it, working on the actual model rather than the list of actions, but I'm not sure how much sense that makes.
