### ISSUE TITLE
vendace - error in runing model with parameters

### ISSUE THREAD

**Issue by vbartolino** [gadget-framework/gadget3#4]
I'm adapting the model on Baltic vendace based on the demo-ling example. I get stuck at the following line 
https://github.com/gadget-framework/gadget3/blob/7ba8964575ba1f2d377fdc8291b14d506926c63b/demo-ling/setup.R#L175

that in my case returns:

```> result <- ven_model(ven_param)
Error in ven_model(ven_param) : 
  abs(ven_mat__prevtotal - sum(ven_mat__num[, ven_mat__area_idx,  .... is not TRUE
>
> traceback()
3: stop(simpleError(msg, call = if (p <- sys.parent(1L)) sys.call(p)))
2: stopifnot(abs(ven_mat__prevtotal - sum(ven_mat__num[, ven_mat__area_idx, 
       ven_mat__age_idx])) < 1e-04)
1: ven_model(ven_param)
>
```
 I've tried to ```debug(ven_model)``` to understand what happens but it is too convoluted and deep.
Thankful for any suggestion

**Comment by lentinj** [comment]
That ``stopifnot()`` is part of the growth step (if you look the top of the block of code you should see a ``comment("g3a_grow for ling_mat")`` comment). What the check is checking is if the total number of fish is the same before and after growth. If it isn't, then we fall over.

As for why it isn't, check the parameters you're setting as part of the growth. I'm guessing one is zero, resulting in improbable output from the growth implementation.

**Comment by bthe** [comment]
My guess is that this error is related to stock max length > `Linf` problem that we have been discussing in issue https://github.com/gadget-framework/gadget3/issues/13

**Comment by bthe** [comment]
@vbartolino could you update g3 on your computer and confirm that https://github.com/gadget-framework/gadget3/commit/2ff4dc979aabfb5aa3d98532fc0e0cf850fb9d80 fixed your issue?

**Comment by vbartolino** [comment]
yes it goes through!
I continue my journey down the script...

```
> # Run model with params above
> result <- ven_model(ven_param)
> result[[1]]
[1] 2.624981e+14

> ##### Run TMB-based model ######
> # Turn actions into C++ objective function code
> tmb_ven <- g3_to_tmb(c(
+   ven_mat_actions,
+   ven_imm_actions,
+   fleet_actions,
+   ven_likelihood_actions,
+   list(time)))
Error in seq(start_year, end_year) : object 'start_year' not found
```
