### ISSUE TITLE
Adding likelihood distribution type to report names

### ISSUE THREAD

**Issue by lentinj** [gadget-framework/gadget3#41]
As discussed, it'd be nice if it was ``cdist_surveyindices_...``, and so on.

I've done this, but lots of identifiers change as a result.

Should this also affect the weight parameter names (since they're based on the same string)?
Should we rename ``cdist`` to something else whilst here? The c stands for catch, which isn't particularly relevant now.

**Comment by bthe** [comment]
Yes, catch distribution is a bit of a misnomer, as it is a general prefix for all types observations. Would obs_dist or odist make sense here?

**Comment by lentinj** [comment]
It's not just the observations though, since it'll (currently) be ``cdist_(func_name)_(nll_name)__(model|obs)_(num|wgt)``.

I'm tempted to go with one of:

* ``ldist``: i.e. a shortened form of ``g3l_likelihood``
* ``cdist`` or ``adist`` depending if looking at catch or abundance.

I think the latter is the way to go.

**Comment by lentinj** [comment]
Okay, I'm done playing. There's lots of renames here to be aware of @bthe @willbutler42 :-1: 

* lln weight parameters will now look like ``cdist_sumofsquares_ldist_lln_weight`` or ``adist_surveyindices_log_surveyindices_weight``.
* Abundance variables now look like ``cdist_sumofsquares_ldist_lln_model__num`` or ``adist_surveyindices_log_surveyindices_model__num``.
* There's no ``g3l_distribution()`` anymore, either call ``g3l_catchdistribution`` or ``g3l_abundancedistribution``.

I've tried to do appropriate renames in demo-ling, apologies if I missed anything!
