### ISSUE TITLE
g3_tmb_relist output missing unoptimised values

### ISSUE THREAD

**Issue by lentinj** [gadget-framework/gadget3#42]
Whist it correctly only expects values in ``par`` to be for optimized values, unoptimized values should be added back in afterwards to do what it says on the tin.

**Comment by lentinj** [comment]
@willbutler42 g3_tmb_relist should be sorted with the above

**Comment by willbutler42** [comment]
> @willbutler42 g3_tmb_relist should be sorted with the above

Great, thanks
