### ISSUE TITLE
Quota decision action for projections

### ISSUE THREAD

**Issue by lentinj** [gadget-framework/gadget3#43]
When doing a projection, you would want to model a quota decision process, which would, after inspecting (e.g.) fleet output, abundance, and predator consumption, produce a quota value that would get used by the fleets until the next decision point.

Somewhat similar to ``g3l_distribution``, there would need to be an aggregation step and a point where a decision is made which sets the quota value. However, ``g3l_distribution``'s behaviour is driven by the source data, that obviously doesn't exist here.

How much commonality is there in a aggregation step?

* Can we assume that a quota decision will be based totals from a set of variables? Or would you do be doing more interesting things per-timestep as part of the decision process?
* Do the outputs (always) need to be aggregated over other dimensions (age & area)?

Also, note to self: There's an emerging pattern of iterate/finalise pairs of formulas, which may be worth formalising a bit more.

**Comment by bthe** [comment]
I would envisage that you would like to be able to define a number of these decision processes during the simulation, similar to how you define other processes,  that will only take effect during a predefined set of timesteps. In the extreme a decision function would involve a full gadget assessment on top of the simulation step so having access to a time series of unaggregated abundance/biomass, consumption and catch by stock is going to be useful.

**Comment by bthe** [comment]
> Also, note to self: There's an emerging pattern of iterate/finalise pairs of formulas, which may be worth formalising a bit more.

Are you thinking along the lines of Rgadget's `gadget_update` and  `gadget_discard` ?

**Comment by lentinj** [comment]
> Are you thinking along the lines of Rgadget's gadget_update and gadget_discard ?

No, more like how spawning is defined in terms of an ``r`` and ``s``, where one is a running total and the other a finalisation for the value. The formulas are basically used like ``stock_iterate(stock, if (run_f) x <- x + s) ; x <- r``. Feels like a more direct way of doing the above might be useful.

As for ``gadget_update`` and ``gadget_discard``, it's a case of manipulating the list of actions to match an action within, to then replace/remove it. Obviously this is going to come up with gadget.fit. Looking at the step names with a regex seems like a good starting point

**Comment by lentinj** [comment]
This is being done in https://github.com/gadget-framework/gadget3/issues/66
