### ISSUE TITLE
Prune unnecessary parameters from a model

### ISSUE THREAD

**Issue by bthe** [gadget-framework/gadget3#5]
I'm thinking about my options when defining the initial numbers at age and number of recruits. One solution, that I think could be interesting would be to define the initial numbers of age (before discounting for natural mortality and an equilibrium fishing mortality) and the number of recruits as a single parameter table. The obvious benefits of this approach would come when defining recruitment as a random effect. The only way I can think of this something like this is:

```
ling_init_abund <-
  ~g3_param("ling.scalar") * exp(g3_param_table("ling.init", expand.grid(cur_year = seq(start_year, end_year),
                                           age = seq(
                                             min(ling_imm__minage, ling_mat__minage),
                                             max(ling_imm__maxage, ling_mat__maxage)))))

```

which introduces a very large number of unnecessary variables as I'm only interested in using the edges of the table. Is there a way to purge these unnecessary variables?

**Comment by lentinj** [comment]
Edges of ``cur_year`` dimension, presumably? So what you need is something like:

```
is_step_init <- ~min(cur_step, 1)
ling_init_abund <-
  ~g3_param("ling.scalar") * exp(g3_param_table("ling.init", expand.grid(is_step_init = c(0, 1),
                                           age = seq(
                                             min(ling_imm__minage, ling_mat__minage),
                                             max(ling_imm__maxage, ling_mat__maxage)))))
```

This might even work :) But regardless we probably want to define it as part of ``g3a_time`` so you don't have to create the definition yourself. There also needs to be some careful naming to indicate the difference between this and ``cur_step_final``, which is a boolean for the current step of the year.

**Comment by bthe** [comment]
Hmm, this looks like you are pulling ling.init for all ages but ignoring the years or am I misinterpreting this?

**Comment by lentinj** [comment]
The idea is to have parameters ``ling.init.0.3``..``ling.init.0.15`` and ``ling.init.1.3``..``ling.init.1.15``. ``is_step_init`` is either 0 for the first step, or 1 otherwise.

Looking back, this does seem a bit ugly though. Another way to do it could be:

```
ling_init_abund <- ~g3_param("ling.scalar") * exp(
    if (cur_step == 0)
        g3_param_table("ling.init", expand.grid(
                                           age = seq(
                                             min(ling_imm__minage, ling_mat__minage),
                                             max(ling_imm__maxage, ling_mat__maxage))))
    else
        g3_param_table("ling.renew", expand.grid(
                                           age = seq(
                                             min(ling_imm__minage, ling_mat__minage),
                                             max(ling_imm__maxage, ling_mat__maxage))))
)
```

And have ``ling.init.3``..``ling.init.15`` and ``ling.renew.3``..``ling.renew.15``. The expression isn't exactly pretty, but a helper could do it for you.

**Comment by bthe** [comment]
I guess what I would like to have is something like:

```
ling_init_abund <- ~g3_param("ling.scalar") * exp(
  if (cur_step == 0)
    g3_param_table("ling.init", expand.grid(
      age = seq(
        min(ling_imm__minage, ling_mat__minage),
        max(ling_imm__maxage, ling_mat__maxage))))
  else
    g3_param_table("ling.renew", expand.grid(
      cur_year = seq(start_year+1, end_year)))
)
```

But this gives me an error.

**Comment by lentinj** [comment]
You want ``cur_time``, not ``cur_step`` (sorry, that was my boo-boo). The former is 0..(# steps in model) the latter is 1..(steps in year)

(FWIW I worked this out by editing the model function and adding a few print() statements in before).

**Comment by lentinj** [comment]
I think this is done? There isn't any obvious ways of making a helper for the above, especially as the 2 tables are quite different. I think it's as good as it's going to get.
