### ISSUE TITLE
Make start_year / end_year / project_years unoptimised parameters by default

### ISSUE THREAD

**Issue by lentinj** [gadget-framework/gadget3#57]
Gadgetutils’ g3_retro() needs to alter the start_year and end_year of a model, which
is currently a lot of work. The defaults for g3a_time() should be unoptimised
parameters so this effort isn’t required. Make sure all examples make best use of this
rather than ignoring it.

This will simplify the effort required to write g3_retro() and similar tools.

**Comment by lentinj** [comment]
@willbutler42 I finally remembered why this is hard at the weekend---``g3_param_table``. For things like ``g3_param_table("ling.rec", data.frame(cur_year = seq(start_year, end_year)))`` to work, ``start_year`` and ``end_year`` need to be defined as part of the model, otherwise we can't work out how many ``ling.rec`` parameters there should be. And on changing the parameter we should in theory create/destroy the corresponding ``ling.rec`` parameters, but there's nowhere for that to happen.

However, this doesn't apply to ``project_years``. I'm thinking the new task list here is:-

* ``project_years`` becomes an unoptimised parameter by default
* Support negative ``project_years`` (meaning stop (x) years before the end), which retro can then use to stop the model early.

**Comment by lentinj** [comment]
I've done the ``project_years`` bit, and g3_retro now uses this: https://github.com/gadget-framework/gadgetutils/commit/0de60c1e462ced55a78c3f0a8204deed31270e19

I think this is all that can be done here. I've not thought of anything else we can do to start_year / end_year by default without breaking lots of existing use-cases.

**Comment by willbutler42** [comment]
Great, thanks @lentinj , having `project_years` as an unoptimized parameter that can be negative sounds like a good solution to me.
