### ISSUE TITLE
Add g3_stock_param from gadgetutils

### ISSUE THREAD

**Issue by lentinj** [gadget-framework/gadget3#58]
Move g3_stock_param() from gadgetutils into gadget3 itself. Make use of this to
make the defaults for g3a_initial_vonb() parameters, removing the need for the
custom version in gadgetutils.

**Comment by willbutler42** [comment]
@lentinj Ah, I cannot think of any reason for this, so both gadget-models should use the gadgetutils implementation. For it to work, would just need to change 'initv' to 'init' on line 137 of:

 https://github.com/gadget-framework/gadget-models/blob/master/06-ling/gadget3/00-setup/setup.R

**Comment by lentinj** [comment]
Okay, that should do it: https://github.com/gadget-framework/gadget-models/commit/bb9bcafe2ff709e9cb3bc65ad7e013850a262e7b

**Comment by willbutler42** [comment]
@lentinj It would be a nice addition to have a simple default initial conditions method. You are thinking along the lines of just passing the stock to `g3a_intiialconditions_normalparam` and having the parameters defined within? If so, I think a parameter per age group per stock is the 'go-to' method (not sure why I didn´t make this the default in gadgetutils!)

https://github.com/gadget-framework/gadgetutils/blob/main/R/setup-utils.R#L81

**Comment by lentinj** [comment]
Yeah, looking at gadget-models I think you could condense it down to not much more than ``g3a_initialconditions_simple(c(ling_imm, ling_mat), init_mode)``, that returns both ``g3a_initialconditions_normalparam()`` actions for you.

I'd be tempted to have one function per-mode instead meself. Of course, the downside of that is you then have 3 things to name...

**Comment by lentinj** [comment]
Similarly, I'm now looking at ``init_sd()``, however I can't replicate this using ``gadgetutils::init_sd``:

https://github.com/gadget-framework/gadget-models/blob/bb9bcafe2ff709e9cb3bc65ad7e013850a262e7b/06-ling/gadget3/src/step-utils.R#L33-L37

There, we have an ``id``parameter, which is handed to ``init_vonb``, and the parameter id is hard-coded as "species". Here it's the other way around.

I'm guessing practically this isn't an issue, since everything is "species" whenever it's actually used, however it feels like something that shouldn't be ignored. ``init_sd`` should either:-

* Have 2 ``id`` parameters, one for initial_sigma_*, one for vonb
* Use the same "id" parameter for both, and not hard-code species.

Which is more sensible? The former would be safest, but seems silly to do so if it's just a c+p error.

**Comment by lentinj** [comment]
(where I'm going with all this is trying to weed out all uses of stuff in [R/model_utils.R](https://github.com/gadget-framework/gadget3/blob/master/R/model_utils.R). Whilst _vonb probably ends up in [R/action_renewal.R](https://github.com/gadget-framework/gadget3/blob/master/R/action_renewal.R), the rest may be better off in ``init_abund`` and ``init_sd``, since that's possibly the only time they're used).

**Comment by willbutler42** [comment]
Yup, should remove the hardcoded 'species', and the second option (using the same 'id') is the approach to take in this case.

**Comment by lentinj** [comment]
Okay, what I think is missing here is a ``stock_param()`` that translates the stock names into param names along with all the other stock-renaming magic that goes on in ``g3_step()``. With that, one could define a vonb with parameter defaults much as other plug-in functions:

```
g3a_initialconditions_vonb <- function(
        name_part = NULL,
        Linf = substitute( stock_param(stock, name_part = name_part, 'Linf'), list(name_part = name_part)),
        K = substitute( stock_param(stock, name_part = name_part, 'K'), list(name_part = name_part)),
        recl = substitute( stock_param(stock, name_part = name_part, 'recl'), list(name_part = name_part)),
        K_scale = 0.001) {
    f_substitute(
        ~Linf * (1 - exp(-1 * (K_scale * K) * (age - (1 + log(1 - recl/Linf)/(K_scale*K))))),
        list(K_scale = K_scale,
            Linf = Linf,
            K = K,
            recl = recl))
}
```

...obviously without ``name_part`` this would be even simpler.

Note I'm not even handing in the stock into this function: it gets renamed by ``g3a_initialconditions_normalparam()``, in the same way we can reference ``stock__midlen`` in the output of ``g3a_grow_lengthvbsimple()``.

This makes adding stock param defaults much easier. Having a generic ``g3_param_stock('x', by_year = TRUE, exponeniated = TRUE)`` would be pretty easy.

This doesn't help with parameters by age, over both immature and mature, which gets used for *M*: ``g3_stock_table(list(imm, mat), 'species', 'M')``

We can't rely on this getting auto-renamed, since the action will only have one of the 2 stocks handed in. I'm tempted to argue that separate parameters for ``ling_imm.M.10`` and ``ling_mat.M.10`` make more sense, but my motivation is pretty transparent by this point :)

**Comment by willbutler42** [comment]
So if I understand it correctly, using this example, the references to the vonb parameters will be generated within g3_step, with the full stock name (ie stock$name) if name_part = NULL and specified name_part otherwise? Sounds useful for parameter defaults : )

And regarding g3_param_stock, the principle would be the same, that the param name to stock-param name change would occur automatically?

Haha, yes, we've only really used by-age parameters over two stocks for the initial abundance (mode 1, https://github.com/gadget-framework/gadgetutils/blob/main/R/setup-utils.R#L80) but it is quite a useful tool for testing simplified implementations of initial conditions.

**Comment by lentinj** [comment]
> So if I understand it correctly, using this example, the references to the vonb parameters will be generated within g3_step, with the full stock name (ie stock$name) if name_part = NULL and specified name_part otherwise?

Yup.

> And regarding g3_param_stock, the principle would be the same, that the param name to stock-param name change would occur automatically?

Yup:

```
>  stock_a <- g3_stock(c(t = 'stock', 'aaa'), seq(10, 35, 5))
> gadget3:::g3_step(~stock_param(stock_a, 'parr', optimise = FALSE))
~g3_param("stock_aaa.parr", optimise = FALSE)
> gadget3:::g3_step(~ stock_param(stock_a, 'parr', name_part = 't', lower = 4, upper = 5) )
~g3_param("stock.parr", lower = 4, upper = 5)
```

...and this will happen within ``g3a_initialconditions_normalparam()`` (or whatever), which already has the stock available. So a call might look like:-

```
g3a_initialconditions_normalparam(ling_imm, mean_f = gadget3:::g3a_initialconditions_vonb(name_part = "species"), ...
```

**Comment by willbutler42** [comment]
This looks good and covers most of the cases, it is sometime useful to have groups of parameters, would there be a way to generate, for example: `~if (cur_year < 2000) g3_param("stock.x.early") else g3_param("stock.x.late")`?

**Comment by lentinj** [comment]
Not yet, but it wouldn't be impossible to say that, e.g. ``by_year = list(early = 2000, late = Inf)`` means this. Adding the breakpoints to the g3_param_table would be awkward though.

**Comment by willbutler42** [comment]
Other than that, nothing to add from my end : )

**Comment by lentinj** [comment]
There, I've pushed ``stock_param``, ``stock_param_table`` and ``g3_parameterized``.

I've also got a ``g3_renewal_vonb`` that uses ``g3_parameterized`` for the defaults, which I'll push once I've had a chance to write some tests / documentation. I'm guessing there's lots of other places we could do similar.

**Comment by lentinj** [comment]
Right, there's now finally a ``g3a_renewal_vonb()``, that can do the work of the previous 2 vonb functions.

Note that there's no ``K_scale``, instead the defaults do ``K = g3_parameterized('K', by_stock = by_stock, scale = 0.001)``, which seemed simpler. You could override ``K`` to change this if need be.
