### ISSUE TITLE
Bounded variables

### ISSUE THREAD

**Issue by bthe** [gadget-framework/gadget3#6]
There are a few cases where I would like to ensure that a variable stays within limits. Broadly speaking these limitations fall into two cases, I either want a parameter `x` to be greater than 0 (the reverse is achieve via -x), or be between the values `a` and `b`. To achieve this effect you can define a formula where the gadget parameter is transformed and then substitute into the model formula using `gadget3:::f_substitute`. The case where `x` is greater than `a`, can be ensured by:

```
x_trans = ~exp(x) + a 
```

and the case where  `a < x < b`, you can do the following:

```
x_trans = ~a + (b-a)/(1 + exp(0.01*x))
```
I would expect this is something that the users would like to do on a regular basis, so I would expect that it would make sense to define a wrapper function for these cases.

**Comment by lentinj** [comment]
I'm a bit confused why you're not using ``nlminb()``s lower / upper here. Is ``x_trans`` a derivative of ``x``, and both are used in different parts?

But this is a very similar case to ``logspace_add`` / ``logspace_add_vec`` / ``avoid_zero`` / ``avoid_zero_vec`` in ``aaa_global.R`` and would be easy to add here. In fact they'd do everything apart from the ``a < x < b`` case.

**Comment by bthe** [comment]
> I'm a bit confused why you're not using nlminb()s lower / upper here. Is x_trans a derivative of x, and both are used in different parts?

I've been running into issues with the bounded minimization, have my theories as to why that is but I'm pretty sure I'm wrong:) But at least this allows us to run unconstrained minimization in the case where the optimiser wants explore regions outside the scope of the bounds. It also helps with defining the scale of the parameter, as the optimisers can be pesky about those.

> But this is a very similar case to logspace_add / logspace_add_vec / avoid_zero / avoid_zero_vec in aaa_global.R and would be easy to add here. In fact they'd do everything apart from the a < x < b case.

Exactly, I was more thinking about convenience as I would like to do something along the lines of `g3_param_bounded('x',lower = a, upper=b)`.

**Comment by lentinj** [comment]
So doing the parameter bounding "in software", in effect? With a (simplified) end result of:

```
    PARAMETER(x);
    x = min(max(x, 0), 10);
```

...so no matter what the optimiser sets x to, it always ends up ``0..10``? Are we sure this won't end up confusing the optimiser further?

> ``g3_param_bounded('x',lower = a, upper=b)``

For this case I'd expect to end up with ``bounded(g3_param('x'), a, b)``, but a ``g3_param_bounded`` could be interesting if you want to define the bounds at the same time as the parameter, rather than in ``setup.R`` as now.

**Comment by bthe** [comment]
Exactly, the end result would be to prevent variables from exceeding the bounds. Compared to a repeated application of `logspace_add` the `a + (b-a)/(1+e^x)` approach normalises the variables to a standard range with a center on 0 which can help the optimiser, at least the ling model is starting to converge with less fuzz (sadly not to a sensible minimum though). So we may want allow the user to have different options when defining the bounds. 

In relation to this gadget2 had the option of defining an initial value for the parameter when the variable was defined (i.e. `1#param`). One could imagine that you could do something similar with `g3_param*` at same time you define the bounds.

**Comment by lentinj** [comment]
You can try the following:

```
bounded <- gadget3:::g3_native(r = function (x, a, b) {
    a + (b-a)/(1+exp(x))
}, cpp = '[](Type x, Type a, Type b) -> Type {
    return a + (b-a)/(1+exp(x));
}')

adfn <- g3_tmb_adfun(g3_to_tmb(list(~return(bounded(g3_param("x"), 50, 70)))))
adfn$fn(list(x = 5))
adfn$fn(list(x = -5))
```

If it turns out to be useful then can move the definition into ``aaa_global.R``.

**Comment by bthe** [comment]
I guess this https://github.com/gadget-framework/gadget3/commit/a58e11e7fda6fc6e813dd2faea0c19e9836c1a2e addresses this issue. Closing for now.
