### ISSUE TITLE
f_substitute requires substitutions to be bracketed

### ISSUE THREAD

**Issue by lentinj** [gadget-framework/gadget3#7]
The root of this is substitute() won't add brackets to a language tree, but they get added in as part of deparsing.

```
> substitute(1 - recl / 3, list(recl = quote(4 + 16 / 1)))
1 - (4 + 16/1)/3
> substitute(1 - (recl) / 3, list(recl = quote(4 + 16 / 1)))
1 - (4 + 16/1)/3
```

```
> gadget3:::parse_tree(substitute(1 - recl / 3, list(recl = quote(4 + 16 / 1))))
| symbol -
| num 1
| | symbol /
| | | symbol +
| | | num 4
| | | | symbol /
| | | | num 16
| | | | num 1
| | num 3
> gadget3:::parse_tree(substitute(1 - (recl) / 3, list(recl = quote(4 + 16 / 1))))
| symbol -
| num 1
| | symbol /
| | | symbol (
| | | | symbol +
| | | | num 4
| | | | | symbol /
| | | | | num 16
| | | | | num 1
| | num 3
```

Unfortunately ``g3_to_tmb()`` relies on these bracket functions to not bother with operator precedence. So either we need to add them back in inside f_substitute or g3_to_tmb needs to be aware of precedence.

**Comment by bthe** [comment]
Not sure if this is a related issue, but in the ling demo there is a discrepancy between the TMB and the R version likelihood score (lines 260 vs 181 respectively) for the initial parametrisation, but this discrepancy disappears when I turn of the likelihood score from the survey indices (line 173).

**Comment by lentinj** [comment]
Yup, it is a related issue. Before the above commit:

```
> ling_model(tmb_param$value)[[1]]
[1] 5.653032e+16
> ling_model_tmb$fn(g3_tmb_par(tmb_param))
[1] 5.640679e+16
```

...and after:

```
> ling_model(tmb_param$value)[[1]]
[1] 5.653032e+16
> ling_model_tmb$fn(g3_tmb_par(tmb_param))
[1] 5.653032e+16
```

**Comment by lentinj** [comment]
It's not perfect, f_optimise() could do with noticing things like ``exp((2 + 2))``, but it doesn't have knowledge of context, so can't say if the extra brackets are needed or not. Still, it's better than being buggy :)
