### ISSUE TITLE
Area "all" not accepted by g3l_catchdistribution()

### ISSUE THREAD

**Issue by MikkoVihtakari** [gadget-framework/gadget3#76]
I notice that when I run:

```
g3l_catchdistribution(
    'trawl_ldist',
    TrawlNor_ldist,
    fleets = list(TrawlNor, TrawlRus),
    stocks = stocks,
    g3l_distribution_sumofsquares(),
    nll_breakdown = TRUE,
    report = TRUE)
```

I get:

```
Error in g3l_likelihood_data(nll_name, obs_data, missing_val = missing_val,  : 
  Areas in data don't have integer names, but areas not provided
```

The fix is to mutate the area to integer:

```
g3l_catchdistribution(
    'trawl_ldist',
    TrawlNor_ldist %>% mutate(area = 1), # This hack due to a bug in g3/mfdb
    fleets = list(TrawlNor, TrawlRus),
    stocks = stocks,
    g3l_distribution_sumofsquares(),
    nll_breakdown = nll_breakdown,
    report = lik_report)
```

Uncertain whether this bug comes from `gadget3::g3l_catchdistribution` or `mfdb`

**Comment by lentinj** [comment]
What you want to do is to provide ``area_group``, e.g. ``area_group = c(all = 1)``. It basically does the same thing internally.

The general idea with area support is you'd have a vector of area_names, e.g. ``areas <- c(here = 1, there = 2)``, and use that to define models a bit more logically, e.g. ``g3_livesonareas(names[c('here', 'there')])``.

Obviously you can't do this so easily when providing data.frames. Although we now start defining area constants in gadget3 models, which will eventually make the need for area_group above go away, as we can see if ``area == area_all`` when we need to.

**Comment by MikkoVihtakari** [comment]
Ok, thanks. Seems to be a feature, not a bug, then.

**Comment by lentinj** [comment]
"Feature" is a strong word, I'd like to fix it at some point. But the need for ``area_group`` won't entirely go away, since your data may refer to an aggregation of model areas.

**Comment by MikkoVihtakari** [comment]
Simple fix in 3g3 would be something like

```
if(is.character(x$area)) {
x$area <- as.integer(as.factor(x$area))
}
```

Of course you could also remove the check that area has to  be numeric.

**Comment by lentinj** [comment]
It's not as easy as that, alas (but I've nearly done it multiple times). Say I have a setup like:

```
areas <- c(here = 1, there = 2)
fish <- g3_stock('fish') |> g3_livesonareas(names[c('here', 'there')])
 . . .
g3l_abundancedistribution('abund', data.frame(area = 'there', number = c(1004, 20093, ...)), . . .)
```

We'd substitute "there" => 1 for the abundance distribution, which is wrong since this is actually "here". We should be substituting 2.

Another way of simplifying this is just leaving out the area column entirely, it's entirely optional here. But this may confuse gadgetutils.
