### ISSUE TITLE
Export g3_fit()

### ISSUE THREAD

**Issue by MikkoVihtakari** [gadget-framework/gadget3#77]
g3_fit() seems quite central function. We'll also need to refer to it in gadgetutils plots. Could you export it?

**Comment by lentinj** [comment]
@willbutler42 Right, I've (finally) added a version of g3_fit to gadgetutils. Hopefully it's still useful.

I'll keep this ticket open regardless and the old g3_fit around for a while. If there's no problems after a few months, I'll scrub it.
