### ISSUE TITLE
Error in ...names() : could not find function "...names"

### ISSUE THREAD

**Issue by MikkoVihtakari** [gadget-framework/gadget3#82]
While trying to compile a model on Daniel's Windows machine (R 4.0) we encountered following issue:

```
g3_stock("test", lengthgroups = 1:5) %>% g3s_livesonareas(areas[c('1')])
Error in ...names() : could not find function "...names"
```

`...names()` was [apparently introduced by R 4.1](https://github.com/ropensci/osmextract/issues/241#issuecomment-1030896896). I don't see that this f[unction would have been used in `g3s_livesonareas()`](https://github.com/gadget-framework/gadget3/blob/4480f3402e20d83a5bddb84cda1c0678e8dd275e/R/stock_areas.R), right?

Is it perhaps used by the most recent version of rlang? Or some other tidyverse packages? Can we get rid of those dependencies somehow? Or am I lost with my reasoning?

**Comment by lentinj** [comment]
It's in ``gadget3`` itself:

https://github.com/gadget-framework/gadget3/blob/4420ddca38f342f247a8a2b87f494b335aae113d/R/formula_utils.R#L41-L43

https://github.com/gadget-framework/gadget3/blob/4420ddca38f342f247a8a2b87f494b335aae113d/R/run.R#L65

...in both cases, rewriting wouldn't be too much of a bother. This is being picked up by "oldrel-1", yes?

**Comment by MikkoVihtakari** [comment]
> ...in both cases, rewriting wouldn't be too much of a bother. This is being picked up by "oldrel-1", yes?

No, on a Windows machine with R 4.0.

**Comment by lentinj** [comment]
[oldrel-2](https://api.r-hub.io/rversions/r-oldrel/2) would be 4.0, and pick this up. Seems like a reasonable compromise in what we support.

[Tidyverse policy is oldrel-4](https://www.tidyverse.org/blog/2019/04/r-version-support/). This seems a bit extreme for our purposes though. I'd like to get to 4.1 being the minimum version in the not too distant future, so we can use the native pipe in examples.

Regardless, should update the CI to check this, and add something into the rversions API and auto-update the DESCRIPTION, both here and MFDB.
