### ISSUE TITLE
Estimation of survey catchability coefficients

### ISSUE THREAD

**Issue by bthe** [gadget-framework/gadget3#9]
I know we have gone back and forth with this but I think we need to implement the same type of likelihood function for survey indices that we have in gadget2. At the moment we have 

```
nll = sum((I - (alpha + beta * N))^2)
```
where `alpha` and `beta` are estimable parameters, `I` the index and `N` the model output. In comparison the formulation in gadget2 is roughly (following https://en.wikipedia.org/wiki/Simple_linear_regression ) :

```
beta = sum((I - mean(I))(N - mean(N))/sum((N - mean(N))^2)

alpha = mean(I) - beta * mean(N)
```

The reason for this suggestion is that I think that this formulation is causing all sorts of problems as there is no natural scale for the `alpha` and `beta` parameters.

**Comment by lentinj** [comment]
The guts of how this works in gadget2 are here:

https://github.com/gadget-framework/gadget2/blob/1c614d6540a5f3544d48f58b4a48d8bfc218a524/src/sionstep.cc#L319-L357

We munge data into a ``tmpData`` & ``tmpModel``, throw them into the regression object, and then make up the score from the SSE of the fit.

The regression classes themselves are defined here:

https://github.com/gadget-framework/gadget2/blob/1c614d6540a5f3544d48f58b4a48d8bfc218a524/src/regressionline.cc

So we have to first calculate ``alpha`` & ``beta`` as you've shown, and then work out the sum-of-squares error. Not sounding that scary, although we probably want to break this out into a function to avoid too many headaches.

**Comment by lentinj** [comment]
Yeah, not a hard thing to implement. The interesting part is reporting of ``alpha`` and ``beta`` (which is a pain for gadget2 too: ``//JMB - this is nasty hack to output the regression information``).

My only suggestion so far would be a separate reporting step that recalculates both for reporting, which is a bit naff. Will mull it a bit more to see if I can think of a neater way around.

**Comment by lentinj** [comment]
Right, this is done with the above. Now if you don't supply ``alpha`` or ``beta`` to ``g3l_distribution_surveyindices``, it'll work them out for you using the whole time-series.

The most invasive part of this is swapping the time and area dimensions around in the reporting for surveyindices. We have to do this to get the per-area time-series data we need to make surveyindices work (TMB can only slice dimensions off one end, so ordering is pretty important). This may have upset code downstream of likelihood reporting.

As for reporting ``alpha`` and ``beta``, there's a separate ticket for that apparently, #17
