### ISSUE TITLE
Bounds likelihood action

### ISSUE THREAD

**Issue by lentinj** [gadget-framework/gadget3#99]
Equivalent of https://gadget-framework.github.io/gadget2/userguide/chap-like.html#sec-boundlike, for when the optimisation method is missing bounds.

**Comment by bthe** [comment]
Experimental version can be found at https://github.com/gadget-framework/g3experiments/blob/master/R/likelihood_penalty.R

**Comment by lentinj** [comment]
This got added in commit 3955b97
